# Generated by Django 4.1.4 on 2023-06-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_progressibilityuserprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressibilityuserprofile',
            name='bio',
            field=models.CharField(default='I use Progressibility to progress.', max_length=200),
        ),
    ]
