# Generated by Django 4.1.4 on 2023-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_progressibilityuserprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressibilityuserprofile',
            name='avatar_md5hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
