# Generated by Django 4.1.4 on 2023-07-10 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressibilitytask',
            name='completed',
            field=models.BooleanField(default=datetime.date(2023, 7, 10), verbose_name='completed'),
        ),
    ]
