# Generated by Django 4.1.4 on 2023-07-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0003_alter_progressibilitytask_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressibilitytask',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='deadline'),
        ),
    ]
