# Generated by Django 4.1.4 on 2023-07-10 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress_tracker', '0006_alter_progressibilitytask_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressibilitytask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
