# Generated by Django 4.1.4 on 2023-07-30 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress_tracker', '0007_alter_progressibilitytask_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressibilityTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateadded', models.DateField(auto_now_add=True, null=True, verbose_name='date added')),
                ('trend_name', models.CharField(max_length=100)),
                ('trends', models.JSONField(verbose_name='trends')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
